### PR TITLE
Enclosure for the device

### PR DESCRIPTION
**Pull request by generationmake**
3D printable enclosure for OpenCyphalPicoBase, display and radiation sensor

### CODE REVIEW

**Comment by generationmake** [comment]
Hi @aentinger 
could you please check the data for the enclosure?
Or move to another repository if necessary.
Thanks

**Comment by aentinger** [comment]
Nope, files/folders are good here :+1: .

I'll start a test print.

**Comment by aentinger** [comment]
Hi @generationmake ☕ 👋 

The test print looks mostly good, see images. Your call if you want to update the design.

IMG_20230605_191302_876
IMG_20230605_191255_432
IMG_20230605_191246_499

**Review by aentinger — APPROVED** [review]
LGTM :+1: see images.

**Pull request merged**
